coverage:
  precision: 2
  round: down
  range: "60...100"
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

flags:
  unit:
    paths:
      - src/ble_reticulum/
    carryforward: true
  integration:
    paths:
      - src/ble_reticulum/
    carryforward: true

ignore:
  - "tests/**/*"
  - "**/__pycache__/**"
  - "**/conftest.py"
